defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 240
mem_gb: 64
cpus_per_task: 1
partition: standard        
name: ${name}
additional_parameters:
  account: iecdt
  qos: standard

